### PR TITLE
Wallet: Change style of delete account button

### PR DESCRIPTION
**Pull request by cehali**
# Summary
Change style of delete account button

### CODE REVIEW

**Comment by cehali** [comment]
Before:
image

**Comment by cehali** [comment]
After:
image

**Comment by rzadp** [comment]
Mobile screenshots please?

**Comment by JustynaBroniszewska** [comment]
I think that if there is a lot of existing devices we should make the content scrollable. The screen shouldn't be higher than desktop.

**Comment by rzadp** [comment]
> I think that if there is a lot of existing devices we should make the content scrollable. The screen shouldn't be higher than desktop.

Agree, max-width with overflow: scrollable or something

**Comment by cehali** [comment]
@JustynaBroniszewska @rzadp I implemented your propositions

**Comment by cehali** [comment]
image

**Comment by cehali** [comment]
image

**Comment by cehali** [comment]
image

**Comment by cehali** [comment]
image

**Comment by cehali** [comment]
The newest version:
image
image
image
image
image
image
image

**Pull request merged**
