### PR TITLE
NewDeviceMessage redesign

### PR DESCRIPTION
**Pull request by alexcherman**

### CODE REVIEW

**Comment by alexcherman** [comment]
Screenshot 2019-10-21 at 13 39 46
Screenshot 2019-10-21 at 13 39 21

**Comment by alexcherman** [comment]
@cehali Rebased

**Comment by Marik-D** [comment]
Broken when displaying on wallet's funds page:
image

**Comment by alexcherman** [comment]
Screenshot 2019-10-22 at 10 22 25

**Comment by alexcherman** [comment]
@Marik-D Could you check this PR again?

**Pull request merged**
