### PR TITLE
Load relayer config in wallet

### PR DESCRIPTION
**Pull request by rzadp**
Fix analogical to #1318

### CODE REVIEW

**Comment by Marik-D** [comment]
Shouldn't it be already loaded when sdk is started?

**Comment by rzadp** [comment]
I dont’t know, but it was failing for me when running the wallet locally
using start:dev

**Comment by Marik-D** [comment]
Yes, I had this problem too. The way I fixed it was to wait for `sdk.start` to complete before rendering the app. https://github.com/UniversalLogin/UniversalLoginSDK/pull/1320/files#diff-21fe2ad581fd37458813f15f961f1d8aR11

**Comment by Marik-D** [comment]
Also, since we are fetching config in `sdk.start`, maybe we should make `sdk.fetchRelayerConfig` private to prevent re-fetching

**Pull request closed without merging**
