### PR TITLE
Add warning to connectWithEmoji

### PR DESCRIPTION
**Pull request by cehali**
# Summary
Add warning to connectWithEmoji

### CODE REVIEW

**Comment by cehali** [comment]
image
image

**Comment by Marik-D** [comment]
"Window", not "windows"

**Comment by xitronix** [comment]
- In react the note is not viisble 
image
- I think that this text shold not be written upper case because  it is too annoying. Let's consider `Do not close this window!`

**Comment by cehali** [comment]
@JustynaBroniszewska @xitronix fixed for react
image

**Comment by cehali** [comment]
@xitronix @rzadp 
image
image

**Pull request merged**
