### PR TITLE
Support for nested ENS domain

### PR DESCRIPTION
**Pull request by Amxx**
Current splitting method assumes `label.domain.eth` structure to extract label and domain. This only work because ethers.js autocompletes domain to domain.eth. It will not work with other tld's and with subdomain.

To support `user.subdomain.domain.xyz`, the splitting should be done at the first `.` only, so that `label = user` and `node=subdomain.domain.xyz`. This is what this PR implements

### CODE REVIEW

**Comment by Amxx** [comment]
Failure of the get2ndLevelDomainForm test is expected since I replaced this function. Can someone explain the reason that led to this function being here in the first place ?

**Comment by marekkirejczyk** [comment]
Hi @Amxx,

I think you just implemented similar functionality in a much shorter way :)
I would propose to move implementation to `domain.split(/\.(.*)/)` to the function (so that test passes)
I would also consider renaming function as I think it does something else than the name suggest. The name could be `parseDomain` or `splitDomin` or sth like this.

I guess complicated implementation is here for historical reasons, but not sure anymore.

Marek

**Comment by Amxx** [comment]
If you look at the tests, `john.and.marek.universal-id.eth` is supposed to be slip into `john.and.marek` and `universal-id.eth`. Also `universal-id.eth` is expected to turn into `` and `universal-id.eth`

My split function will return `john`, `and.marek.universal-id.eth` in the first case and `universal-id`, `eth` in the second case

**Comment by marekkirejczyk** [comment]
Fair enough, shall we fix tests?

**Comment by marekkirejczyk** [comment]
Fix and merged in follow-up PR #362

**Pull request closed without merging**
