### PR TITLE
Backup codes prompt

### PR DESCRIPTION
**Pull request by rzadp**

### CODE REVIEW

**Comment by rzadp** [comment]
Screenshot 2019-11-08 at 11 51 42
Screenshot 2019-11-08 at 11 53 33
Screenshot 2019-11-08 at 11 53 50

**Comment by xitronix** [comment]
If we click 'Ok' on the promt, leave backups, backups flow will apeear anyway and show backups codes gereated screen without backups

**Comment by cehali** [comment]
@xitronix The same behaviour was before and there is a task for this in trello.

**Comment by xitronix** [comment]
@cehali Agree. Checked it too.

**Pull request merged**
