### PR TITLE
System architecture diagram in README

### PR DESCRIPTION
**Pull request by canepat**
This PR adds a UML diagram showing the system architecture in the README.

I've tried to identify and describe the interfaces among the Universal Login subsystems and the main external dependencies in order to provide a graphical system overview for newcomers.

I've added a _modeling_ folder to the repository to include the StarUML project file and images.

Moreover I've added a missing description of the optional dev:start parameter introduced by PR #136

### CODE REVIEW

**Comment by canepat** [comment]
It's the StarUML project file containing the model and diagrams, I added it to the repo for future changes.

**Comment by marekkirejczyk** [comment]
I think the project should be well documented and adding overall diagram is a great idea.
I would like to avoid using commercial paid or non-open source tools.
What would you say about using plantUML instead of starUML? 

Relayer don't depend on web3, therefore it should be removed form package.json and the diargam.

**Comment by canepat** [comment]
Sincerely I was doubtful about tool and licensing: I should have asked before, next time I will.

I didn't know PlantUML but it seems really nice so I will redraw the diagram using it, including the Relayer correction.

I will update this same PR if it's OK.

**Comment by marekkirejczyk** [comment]
@canepat Looking forward to your update.

**Comment by canepat** [comment]
I've drawn up the subsystem diagram using PlantUML, adding a distinction between external and internal interfaces and making the interface towards an Ethereum client explicit. I've also updated the interfaces' description in the README accordingly.

My understanding of the system details is still ongoing, so please underline any error. Every suggestion for diagram improvement is welcome.

**Pull request merged**
