### PR TITLE
Wallet selector redesign

### PR DESCRIPTION
**Pull request by JustCaptcha**

### CODE REVIEW

**Comment by JustCaptcha** [comment]
image

**Comment by JustCaptcha** [comment]
image

**Comment by JustCaptcha** [comment]
image

**Comment by JustCaptcha** [comment]
image

**Comment by JustCaptcha** [comment]
image

**Comment by JustynaBroniszewska** [comment]
Hint has changed 

Screenshot 2020-02-07 at 10 49 52

**Pull request merged**
