### PR TITLE
Multisignature support

### PR DESCRIPTION
**Pull request by Giulio2002**
# Summary
add multi-sig support in relayer

## Checklist
- [x] Change is small and easy to review (please split big changes into multiple PRs)
- [x] Change is consistent with architecture
- [x] Change is consistent with test architecture
- [x] Change is consistent with naming conventions
- [x] New code is covered with tests
- [x] Tests related to old code are updated
- [ ] Documentation is up to date with changes

### CODE REVIEW

**Comment by Giulio2002** [comment]
so i have to create another service and import it into WalletService?

**Comment by Giulio2002** [comment]
@marekkirejczyk can you explain what do you mean with pending execution service? should it be inherited by walletService or it must have its own routes?

**Comment by marekkirejczyk** [comment]
Sorry for being slow on this, I will finally be able to take a closer look tomorrow.

**Comment by Giulio2002** [comment]
> Sorry for being slow on this, I will finally be able to take a closer look tomorrow.

Actually, I would like a clarification on the question i asked you

> @marekkirejczyk can you explain what do you mean with pending execution service? should it be inherited by walletService or it must have its own routes?

**Pull request merged**
